//Redux constant

export const FETCH_USERS_DATA = "FETCH_USERS_DATA";
export const FETCH_USER_DETAILS_DATA = "FETCH_USER_DETAILS_DATA";
export const POST_USER_DATA = "POST_USER_DATA";
export const DELETE_USER_DATA = "DELETE_USER_DATA";
